#!/usr/bin/env bash

set -euo pipefail

PIPELINE_DIR="$(dirname $0)/pipelines"
TARGET="net"

fly \
  --target "${TARGET}" \
  set-pipeline \
  --pipeline "routing-perf-release" \
  --config "${PIPELINE_DIR}/routing-perf-release.yml"
